version: "3.8"
services:
  bot:
    build: .
    volumes:
      - .:/app
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - MONGO_URI=${MONGO_URI}  # Add MongoDB URI to environment variables
      - PORT=${PORT}
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
